// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Net5.Deployment.API.Infrastructure.Data.Contexts;
using Net5.Deployment.API.Infrastructure.Data.Entities;
using System;

namespace Net5.Deployment.API.Infrastructure.Data.Contexts.Configurations
{
    public partial class AlumnoConfiguration : IEntityTypeConfiguration<Alumno>
    {
        public void Configure(EntityTypeBuilder<Alumno> entity)
        {
            entity.ToTable("Alumno");

            entity.Property(e => e.AlumnoId).HasDefaultValueSql("(newid())");

            entity.Property(e => e.Nombres).IsRequired();

            entity.Property(e => e.Apellidos).IsRequired();

            entity.Property(e => e.Edad).IsRequired();

            entity.Property(e => e.Nivel).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Alumno> entity);
    }
}
