name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build-Deploy-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Build
      run: dotnet build  "Net5.Deployment.API" --configuration Release
    - name: Publish
      run: dotnet publish  "Net5.Deployment.API" -c Release -o Api
    - name: Run Azure appservice Deploy
      uses: azure/webapps-deploy@v2
      with: 
        appname: webnet5api
        publish-profile: ${{ secrets.SECRET_DEPLOYAPINET}}
        package: ./Api
    - name: Test
      run: dotnet test --no-build  "Net5.Deployment.TestNUnit" --verbosity normal    
  Build-Deploy-Web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Build
      run: dotnet build  "WebCliente" --configuration Release
    - name: Publish
      run: dotnet publish  "WebCliente" -c Release -o Apiweb
    - name: Run Azure appservice Deploy
      uses: azure/webapps-deploy@v2
      with: 
        appname: webclientenet5
        publish-profile: ${{ secrets.SECRET_DEPLOY_WEB}}
        package: ./Apiweb
   
    
  
